site_name: David&Doc

theme:
  name: material
  language: zh

  features:
    - tabs

  palette:
    primary: teal
    accent: indigo

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date-localized:
      type: date
  - awesome-pages