site_name: David&Blog

theme:
  name: material
  language: zh

  features:
    - tabs    # 添加横向标题栏

  palette:
    primary: teal     # 页首背景颜色：蓝绿色
    accent: indigo    # 目录选择时展示的颜色：靛青

markdown_extensions:
  - admonition        # 添加提示信息
  - codehilite        # 代码语法高亮
  - pymdownx.tilde    # 在需要删除的文字中间划线

plugins:
  - search
  - git-revision-date-localized:        # 在页面尾部添加最后编辑的时间
      type: date
  - minify:                             # 压缩html文件
      minify_html: true

# 导航栏，左侧目录，用于控制目录的显示，会直接进入docs文件夹
nav:
  - 首页: index.md
  - 纵观古今: 
    - 人的需求: 纵观古今/test.md
  - 横看当前:
    - 测试2: 横看当前/test.md
  - 为我所用: 
    - 测试3: 为我所用/test.md
